# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20b1247f94b51ba50f8872662b24a89cd58887e4a9f069426fcd97739c034513852f76ea08fb5140cbd32f995d35fbace5a81a73e5de41d5c5c956dd8ba189e7

test:
  secret_key_base: 13d1b4f8fbd4dc8f6d5a742c79c2409141179b73fc27f0c30811f8cba08b949d5decf6575ee793f497a119792deb5277f54b5203b73cdf9e693e4edbdb5f5e4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
